### PR TITLE
Update poster image

### PR DESCRIPTION
**Pull request by duarte**
/cc @gidsg

### CODE REVIEW

**Comment by mr-mr** [comment]
Not for this PR
Is there a cleaner way for us to do this in the future? Seems arduous if editorial want to make many changes...

👍

**Comment by gidsg** [comment]
Good point @mr-mr right now we don't have any kind of templating system that injects into the CSS but I can have a think about this if it gets too annoying.

**Comment by duarte** [comment]
What I've done before is just have the image link in the spreadsheet — wouldn't that solve it?

**Comment by gidsg** [comment]
@duarte I don't think this would work with the current `sheettodom` implementation as it only sets the `innerHTML` of elements and this would require changing the style attribute or CSS.

**Pull request merged**
