### PR TITLE
use sheet value for trailer title

### PR DESCRIPTION
**Pull request by akash1810**
doesn't look identical, but close enough for the benefit of setting the value from the sheet

before
screen shot 2016-10-05 at 18 42 46

after
screen shot 2016-10-05 at 18 42 57

### CODE REVIEW

**Comment by duarte** [comment]
Hey, can we hold this one till early next week?
It would be nice to have the typeface weight of the title depend on what the next film is, or do something different — just would like to hear from Charlie about the next one before we go ahead with this change.

**Comment by gidsg** [comment]
Hmm, I don't actually see in this PR where the title gets pulled in from the sheet?

**Comment by akash1810** [comment]
@gidsg its done with some data attribute magic - https://github.com/guardian/docs-interactive-template/blob/master/src/js/text/main.html#L68. I don't know how the magic works though.

**Comment by gidsg** [comment]
OK that's fine, just confused because that change wasn't part of this PR.

**Comment by akash1810** [comment]
yeah, sorry - I should have mentioned that in the description.

**Comment by akash1810** [comment]
hey @duarte any update from Charlie?

**Comment by akash1810** [comment]
no longer relevant - closing

**Pull request closed without merging**
