### PR TITLE
replace youtube-iframe-player with youtube-player

### PR DESCRIPTION
**Pull request by akash1810**
branched off of #74 (that needs to be merged in before this gets reviewed)

[youtube-player](https://github.com/gajus/youtube-player) wraps the loading of the yt api in a promise, so it should be fully loaded before we do anything with it.

It also supports multiple players.

### CODE REVIEW

**Comment by gidsg** [comment]
I think if you close this PR and open it compared to your other PR, maybe it will fix the conflict?

**Comment by gidsg** [comment]
👍 💃 (if you fix conflict)

**Comment by akash1810** [comment]
rebased now, everything looks ok in DEV but more 👀 appreciated!

**Comment by gidsg** [comment]
Looks good to me 🍵 👍

**Pull request merged**
